block.key = action.llm_movement
action.param[0].key = enable
action.param[0].unit = none
action.param[0].default = 1  
action.param[0].value[0] = Disabled
action.param[0].value[1] = Enabled

action.param[1].key = update_llm_interval
action.param[1].unit = seconds
action.param[1].default = 86400.0

action.param[2].key = update_history_interval
action.param[2].unit = seconds
action.param[2].default = 86400.0
